// Shared visual language for the Hangry explainer.
//
// Kept in one file so the whole video can be re-skinned from here — the scenes
// never hardcode a colour. The palette is deliberately small: a dark ground, one
// off-white for the figure and type, and a single hot accent that only ever means
// "this is the stress response". Letting the accent mean one thing is what makes
// the escalation legible without narration.

export const COLORS = {
  bg: "#12131A",
  bgAlt: "#1B1D27",
  ink: "#F2EFE6", // stickman + primary type
  inkDim: "#8C8C99",
  accent: "#FF4D2E", // hunger / stress / the hot signal
  accentSoft: "#FF8A6B",
  cool: "#4DD5C4", // the calm state, and the resolution
  amber: "#FFB020", // glucose
} as const;

// Impact-class stack for headlines. No webfont download, so it renders identically
// in Studio and in a headless render.
export const FONT_DISPLAY =
  '"Arial Black", "Arial Bold", Impact, Haettenschweiler, "Segoe UI Black", sans-serif';
export const FONT_BODY =
  '"Segoe UI", "SF Pro Text", Helvetica, Arial, sans-serif';

export const FPS = 30;

/** Scene boundaries in frames. Single source of truth — Root.tsx derives the
 *  total duration from LAST.end, so adding a scene cannot desync the two.
 *
 *  These are GENERATED by generate_vo.py from the measured length of each
 *  voiceover file. The animation follows the voice: forcing speech into
 *  pre-chosen windows is what makes explainer VO sound rushed. If you re-record
 *  or re-word the VO, re-run that script and paste its output here rather than
 *  editing these by hand. */
export const SCENES = {
  coldOpen: { start: 0, end: 452 },
  glucose: { start: 452, end: 939 },
  cortisol: { start: 939, end: 1494 },
  prefrontal: { start: 1494, end: 2169 },
  serotonin: { start: 2169, end: 2745 },
  theFix: { start: 2745, end: 3500 },
} as const;

/** Frames of silence before each scene's VO starts. The cold open holds long
 *  enough for the snap to play unnarrated — the joke dies under narration. */
export const VO_LEAD_IN = {
  coldOpen: 180,
  glucose: 20,
  cortisol: 20,
  prefrontal: 20,
  serotonin: 20,
  theFix: 20,
} as const;

export const TOTAL_FRAMES = SCENES.theFix.end;

export const sceneDuration = (s: { start: number; end: number }) =>
  s.end - s.start;
